/*
 * This file is part of EasyRPG Player (Chaos Fork).
 *
 * EasyRPG Player is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * EasyRPG Player is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with EasyRPG Player. If not, see <http://www.gnu.org/licenses/>.
 */

#include "ai_rewriter.h"
#include "../output.h"

#include <chrono>
#include <cstring>
#include <mutex>
#include <sstream>
#include <curl/curl.h>
#include <fstream>
#include <ctime>
#include <cstdlib>
#include <sys/stat.h>
#ifdef _WIN32
#include <direct.h>
#define mkdir(path, mode) _mkdir(path)
#ifndef S_ISDIR
#define S_ISDIR(m) (((m) & _S_IFMT) == _S_IFDIR)
#endif
#endif

namespace {

// ── State ──────────────────────────────────────────────────────────────────────
bool ai_rewriter_enabled = false;

// Rate-limit: minimum 5 seconds between generations
using Clock = std::chrono::steady_clock;
Clock::time_point last_call_time{};
constexpr auto RATE_DELAY = std::chrono::seconds(5);

// Cached rewritten messages for the current event
struct CachedMessage {
	std::vector<std::string> original;
	std::vector<std::string> rewritten;
};
std::vector<CachedMessage> cached_entries;
size_t cached_index = 0;
uintptr_t cached_event_id = 0;

// Overflow queue: extra message boxes generated by word-wrapping
std::vector<std::vector<std::string>> overflow_queue;

constexpr int MAX_LINES_PER_BOX = 4;
constexpr int MAX_CHARS_PER_LINE = 50;
constexpr int MAX_CHARS_PER_LINE_FACE = 38; // face takes ~72px, leaving ~232px / 6px ≈ 38 chars

// ── Memory System ──────────────────────────────────────────────────────────────
struct MemoryEntry {
	std::string original;   // compact summary of original dialogue
	std::string rewritten;  // compact summary of rewritten dialogue
	int64_t timestamp = 0;  // unix timestamp
};

// Short-term: current session only, not persisted
std::vector<MemoryEntry> short_term_memory;
constexpr size_t MAX_SHORT_TERM = 20;

// Long-term: persisted to disk
std::vector<MemoryEntry> long_term_memory;
std::string memory_notes; // AI-generated summary notes
int session_count = 0;
constexpr size_t MAX_LONG_TERM = 100;

bool memory_loaded = false;

// ── Inworld API configuration ──────────────────────────────────────────────────
constexpr const char* API_URL      = "https://api.inworld.ai/v1/chat/completions";
constexpr const char* API_KEY      = "";
constexpr const char* MODEL        = "mistrai-ai/mistral-large-3";

constexpr const char* SYSTEM_PROMPT =
	"You are the world's funniest dialogue rewriter. "
	"Your job is to take RPG game dialogue and rewrite it in the style of "
	"Snapcube's Real-Time Fandubs (like the Sonic, Shadow, and SA2 dubs). "
	"Rules:\n"
	"- Keep the SAME number of message boxes as the input (this is critical).\n"
	"- You can use as many lines as you want per message box.\n"
	"- Be absurd, irreverent, and hilarious.\n"
	"- Characters should be dramatic, unhinged, and self-aware.\n"
	"- Include Snapcube-style humor: characters breaking the 4th wall, "
	"misunderstanding the plot, flexing about random things, or dropping "
	"iconic lines like 'I've come to make an announcement'.\n"
	"- If someone is a villain, make them hilariously petty.\n"
	"- If someone is a hero, make them absurdly confident or confused.\n"
	"- Output ONLY the rewritten lines, one per line. No numbering, no quotes, "
	"no extra commentary.\n"
	"- Do NOT use any markdown formatting. No asterisks, no bold, no italics, "
	"no headers, no bullet points, no code blocks. Plain text only.\n"
	"- You ARE allowed to swear freely (shit, fuck, damn, ass, hell, etc.) for comedic effect. "
	"Profanity fits the Snapcube fandub energy. However, NEVER use slurs "
	"(racial, homophobic, ableist, or any other kind). Keep it funny, not hateful.\n"
	"\n"
	"MEDIA TO REFERENCE (mix these in naturally):\n"
	"- Snapcube Fandubs: Sonic, Shadow, SA2, Resident Evil, Metal Gear\n"
	"- Anime: JoJo's Bizarre Adventure, Dragon Ball Z, Neon Genesis Evangelion, "
	"Attack on Titan, Naruto, One Piece, Death Note, Fullmetal Alchemist, "
	"Mob Psycho 100, Chainsaw Man, Spy x Family, Bocchi the Rock\n"
	"- Movies/TV: Shrek, The Bee Movie, Morbius, Twilight, Breaking Bad, "
	"The Room, Star Wars prequels, Marvel MCU, The Office, It's Always Sunny, "
	"Legally Blonde, Mean Girls, Kung Fu Panda, Megamind\n"
	"- Games: Undertale, Dark Souls, Metal Gear Solid, Ace Attorney, "
	"Kingdom Hearts, Final Fantasy VII, Persona 5, Minecraft, Among Us, "
	"Five Nights at Freddy's, Danganronpa, Yakuza/Like a Dragon, Elden Ring\n"
	"- RPG Maker Games: Okegom/Deep-Sea Prisoner games (The Gray Garden, "
	"Wadanohara and the Great Blue Sea, Mogeko Castle, Ice Scream), "
	"OneShot, Yume Nikki, Ib, The Witch's House, Mad Father, Misao, "
	"LISA: The Painful, OFF by Mortis Ghost, Corpse Party, "
	"To the Moon, Omori, RPG Maker horror game culture in general\n"
	"- Internet/Memes: Vine compilations, 'is this a pigeon?', "
	"'it's free real estate', loss.jpg, 'do you are have stupid', "
	"'he turned himself into a pickle', Rickrolling, 'and I took that personally', "
	"'we live in a society', 'I fear no man but that thing it scares me', "
	"'confused screaming', copypastas, TikTok/YouTube brain rot\n"
	"- Music: Never Gonna Give You Up, All Star by Smash Mouth, "
	"Livin' on a Prayer, What is Love, Careless Whisper, Megalovania, "
	"Running in the 90s, Cruel Angel's Thesis, Unravel\n"
	"- Creepypasta: Sonic.exe, Ben Drowned (Majora's Mask), "
	"Slenderman, Jeff the Killer, Eyeless Jack, Smile Dog, "
	"Herobrine (Minecraft), Lavender Town Syndrome, "
	"Squidward's Suicide/Red Mist, Candle Cove, The Backrooms, "
	"SCP Foundation, Zalgo, Happy Appy, NES Godzilla Creepypasta, "
	"Pokemon Lost Silver, .exe game culture in general\n"
	"- Operating Systems: Windows XP/Vista/7 nostalgia, Linux elitism, "
	"'I use Arch btw', Clippy, Blue Screen of Death, sudo rm -rf, "
	"'have you tried turning it off and on again', MS Paint, "
	"macOS vs Windows vs Linux wars, TempleOS, "
	"Windows Update interrupting everything\n";

// ── curl write callback ────────────────────────────────────────────────────────
size_t WriteCallback(char* ptr, size_t size, size_t nmemb, void* userdata) {
	auto* response = static_cast<std::string*>(userdata);
	response->append(ptr, size * nmemb);
	return size * nmemb;
}

// ── Minimal JSON helpers (no external JSON lib required) ───────────────────────
// Escape a string for embedding in JSON
std::string JsonEscape(const std::string& s) {
	std::string out;
	out.reserve(s.size() + 16);
	for (char c : s) {
		switch (c) {
			case '"':  out += "\\\""; break;
			case '\\': out += "\\\\"; break;
			case '\n': out += "\\n";  break;
			case '\r': out += "\\r";  break;
			case '\t': out += "\\t";  break;
			default:   out += c;      break;
		}
	}
	return out;
}

// Extract the value of "content" from the first choice in the response JSON.
// This is a deliberately minimal parser — we only need one field.
std::string ExtractContent(const std::string& json) {
	// Find "choices" array, then "message", then "content"
	const std::string key = "\"content\"";
	// We want the content inside choices[0].message.content
	auto choices_pos = json.find("\"choices\"");
	if (choices_pos == std::string::npos) return {};

	auto content_pos = json.find(key, choices_pos);
	if (content_pos == std::string::npos) return {};

	// Find the colon after "content"
	auto colon = json.find(':', content_pos + key.size());
	if (colon == std::string::npos) return {};

	// Skip whitespace to find opening quote
	auto start = json.find('"', colon + 1);
	if (start == std::string::npos) return {};
	++start; // skip the quote

	// Read until unescaped closing quote
	std::string result;
	for (size_t i = start; i < json.size(); ++i) {
		if (json[i] == '\\' && i + 1 < json.size()) {
			char next = json[i + 1];
			switch (next) {
				case '"':  result += '"';  break;
				case '\\': result += '\\'; break;
				case 'n':  result += '\n'; break;
				case 'r':  result += '\r'; break;
				case 't':  result += '\t'; break;
				default:   result += next; break;
			}
			++i;
		} else if (json[i] == '"') {
			break;
		} else {
			result += json[i];
		}
	}
	return result;
}

// Split text by newlines, trimming empty trailing lines
std::vector<std::string> SplitLines(const std::string& text) {
	std::vector<std::string> lines;
	std::istringstream stream(text);
	std::string line;
	while (std::getline(stream, line)) {
		// Trim trailing \r
		if (!line.empty() && line.back() == '\r') {
			line.pop_back();
		}
		lines.push_back(std::move(line));
	}
	// Remove empty trailing lines
	while (!lines.empty() && lines.back().empty()) {
		lines.pop_back();
	}
	return lines;
}

// Extract leading whitespace from a line. Returns {whitespace, rest}.
std::pair<std::string, std::string> SplitLeadingWhitespace(const std::string& line) {
	size_t pos = 0;
	while (pos < line.size() && (line[pos] == ' ' || line[pos] == '\t')) {
		++pos;
	}
	return {line.substr(0, pos), line.substr(pos)};
}

// Strip RPG Maker text formatting codes (\C[n], \N[n], \V[n], \S[n], \!, etc.)
std::string StripFormatCodes(const std::string& text) {
	std::string result;
	for (size_t i = 0; i < text.size(); ++i) {
		if ((text[i] == '\\' || text[i] == '$') && i + 1 < text.size()) {
			char next = text[i + 1];
			// Bracket parameter: \X[n]
			if (std::isalpha(static_cast<unsigned char>(next)) &&
				i + 2 < text.size() && text[i + 2] == '[') {
				auto end = text.find(']', i + 3);
				if (end != std::string::npos) {
					i = end;
					continue;
				}
			}
			// Single-char codes
			if (next == '!' || next == '.' || next == '|' || next == '>' ||
				next == '<' || next == '^' || next == '\\' || next == '$' || next == '_') {
				++i;
				continue;
			}
		}
		result += text[i];
	}
	return result;
}

// Word-wrap a single line, breaking at word boundaries.
std::vector<std::string> WordWrap(const std::string& prefix, const std::string& text, bool has_face) {
	std::vector<std::string> result;
	int char_limit = has_face ? MAX_CHARS_PER_LINE_FACE : MAX_CHARS_PER_LINE;
	int max_content = char_limit - static_cast<int>(prefix.size());
	if (max_content < 10) max_content = 10; // safety floor

	std::string remaining = text;
	while (!remaining.empty()) {
		if (static_cast<int>(remaining.size()) <= max_content) {
			result.push_back(prefix + remaining);
			break;
		}
		// Find last space within limit
		int cut = max_content;
		while (cut > 0 && remaining[cut] != ' ') {
			--cut;
		}
		if (cut == 0) cut = max_content; // no space found, hard break

		result.push_back(prefix + remaining.substr(0, cut));
		// Skip the space at the break point
		size_t next = cut;
		while (next < remaining.size() && remaining[next] == ' ') ++next;
		remaining = remaining.substr(next);
	}
	if (result.empty()) result.push_back(prefix);
	return result;
}

// Split a block of lines into 4-line message box chunks.
std::vector<std::vector<std::string>> SplitIntoBoxes(const std::vector<std::string>& lines) {
	std::vector<std::vector<std::string>> boxes;
	for (size_t i = 0; i < lines.size(); i += MAX_LINES_PER_BOX) {
		std::vector<std::string> box;
		for (size_t j = i; j < lines.size() && j < i + MAX_LINES_PER_BOX; ++j) {
			box.push_back(lines[j]);
		}
		boxes.push_back(std::move(box));
	}
	if (boxes.empty()) boxes.push_back({});
	return boxes;
}

// ── Memory JSON helpers ────────────────────────────────────────────────────────

// Read a JSON string value by key (first occurrence in the given text)
std::string JsonReadString(const std::string& json, const std::string& key) {
	std::string search = "\"" + key + "\"";
	auto pos = json.find(search);
	if (pos == std::string::npos) return {};

	auto colon = json.find(':', pos + search.size());
	if (colon == std::string::npos) return {};

	auto start = json.find('"', colon + 1);
	if (start == std::string::npos) return {};
	++start;

	std::string result;
	for (size_t i = start; i < json.size(); ++i) {
		if (json[i] == '\\' && i + 1 < json.size()) {
			char next = json[i + 1];
			switch (next) {
				case '"':  result += '"';  break;
				case '\\': result += '\\'; break;
				case 'n':  result += '\n'; break;
				case 'r':  break;
				case 't':  result += '\t'; break;
				default:   result += next;  break;
			}
			++i;
		} else if (json[i] == '"') {
			break;
		} else {
			result += json[i];
		}
	}
	return result;
}

// Read a JSON integer value by key
int64_t JsonReadInt(const std::string& json, const std::string& key) {
	std::string search = "\"" + key + "\"";
	auto pos = json.find(search);
	if (pos == std::string::npos) return 0;

	auto colon = json.find(':', pos + search.size());
	if (colon == std::string::npos) return 0;

	size_t start = colon + 1;
	while (start < json.size() && (json[start] == ' ' || json[start] == '\t' || json[start] == '\n')) ++start;

	return std::strtoll(json.c_str() + start, nullptr, 10);
}

// Find the end of a JSON object starting at '{', accounting for strings
size_t FindJsonObjectEnd(const std::string& json, size_t start) {
	if (start >= json.size() || json[start] != '{') return std::string::npos;

	int depth = 0;
	bool in_string = false;
	for (size_t i = start; i < json.size(); ++i) {
		if (in_string) {
			if (json[i] == '\\') { ++i; continue; }
			if (json[i] == '"') in_string = false;
		} else {
			if (json[i] == '"') in_string = true;
			else if (json[i] == '{') ++depth;
			else if (json[i] == '}') { --depth; if (depth == 0) return i; }
		}
	}
	return std::string::npos;
}

// Parse the "entries" array from memory JSON
std::vector<MemoryEntry> JsonReadEntries(const std::string& json) {
	std::vector<MemoryEntry> entries;

	auto arr_key = json.find("\"entries\"");
	if (arr_key == std::string::npos) return entries;

	auto arr_start = json.find('[', arr_key);
	if (arr_start == std::string::npos) return entries;

	// Find matching ]
	int depth = 1;
	size_t arr_end = arr_start + 1;
	bool in_str = false;
	while (arr_end < json.size() && depth > 0) {
		if (in_str) {
			if (json[arr_end] == '\\') { ++arr_end; }
			else if (json[arr_end] == '"') in_str = false;
		} else {
			if (json[arr_end] == '"') in_str = true;
			else if (json[arr_end] == '[') ++depth;
			else if (json[arr_end] == ']') --depth;
		}
		++arr_end;
	}

	// Parse individual objects
	size_t pos = arr_start + 1;
	while (pos < arr_end) {
		auto obj_start = json.find('{', pos);
		if (obj_start == std::string::npos || obj_start >= arr_end) break;

		auto obj_end = FindJsonObjectEnd(json, obj_start);
		if (obj_end == std::string::npos) break;

		std::string obj = json.substr(obj_start, obj_end - obj_start + 1);

		MemoryEntry e;
		e.original = JsonReadString(obj, "original");
		e.rewritten = JsonReadString(obj, "rewritten");
		e.timestamp = JsonReadInt(obj, "timestamp");
		entries.push_back(std::move(e));

		pos = obj_end + 1;
	}

	return entries;
}

// ── Memory file path helpers ───────────────────────────────────────────────────

bool MakeDirectoryRecursive(const std::string& path) {
	size_t pos = 0;
	while (pos < path.size()) {
		pos = path.find('/', pos + 1);
		if (pos == std::string::npos) pos = path.size();
		std::string sub = path.substr(0, pos);
		if (!sub.empty()) {
			mkdir(sub.c_str(), 0755); // ignore errors for existing dirs
		}
	}
	struct stat st;
	return stat(path.c_str(), &st) == 0 && S_ISDIR(st.st_mode);
}

std::string GetMemoryDir() {
	const char* xdg = std::getenv("XDG_CONFIG_HOME");
	std::string dir;
	if (xdg && xdg[0]) {
		dir = xdg;
	} else {
		const char* home = std::getenv("HOME");
		if (home) {
			dir = std::string(home) + "/.config";
		} else {
			return {};
		}
	}
	return dir + "/EasyRPG/Player";
}

std::string GetMemoryPath() {
	std::string dir = GetMemoryDir();
	if (dir.empty()) return {};
	return dir + "/ai_memory.json";
}

void SaveMemoryToFile() {
	std::string path = GetMemoryPath();
	if (path.empty()) return;

	std::string dir = GetMemoryDir();
	if (!MakeDirectoryRecursive(dir)) {
		Output::Warning("Chaos AI Memory: failed to create directory {}", dir);
		return;
	}

	std::ofstream file(path);
	if (!file.is_open()) {
		Output::Warning("Chaos AI Memory: failed to open {} for writing", path);
		return;
	}

	file << "{\n";
	file << "  \"version\": 1,\n";
	file << "  \"session_count\": " << session_count << ",\n";
	file << "  \"notes\": \"" << JsonEscape(memory_notes) << "\",\n";
	file << "  \"entries\": [\n";
	for (size_t i = 0; i < long_term_memory.size(); ++i) {
		file << "    {\"original\": \"" << JsonEscape(long_term_memory[i].original)
			 << "\", \"rewritten\": \"" << JsonEscape(long_term_memory[i].rewritten)
			 << "\", \"timestamp\": " << long_term_memory[i].timestamp << "}";
		if (i + 1 < long_term_memory.size()) file << ",";
		file << "\n";
	}
	file << "  ]\n";
	file << "}\n";

	file.close();
	Output::Debug("Chaos AI Memory: saved {} entries to {}", long_term_memory.size(), path);
}

void LoadMemoryFromFile() {
	if (memory_loaded) return;
	memory_loaded = true;

	std::string path = GetMemoryPath();
	if (path.empty()) return;

	std::ifstream file(path);
	if (!file.is_open()) {
		Output::Debug("Chaos AI Memory: no memory file at {} (starting fresh)", path);
		return;
	}

	std::string json((std::istreambuf_iterator<char>(file)),
					  std::istreambuf_iterator<char>());
	file.close();

	session_count = static_cast<int>(JsonReadInt(json, "session_count"));
	memory_notes = JsonReadString(json, "notes");
	long_term_memory = JsonReadEntries(json);

	Output::Debug("Chaos AI Memory: loaded {} entries, {} sessions, notes: {}chars",
		long_term_memory.size(), session_count, memory_notes.size());
}

// Compact a multi-line dialogue block into a single summary line
std::string CompactDialogue(const std::vector<std::string>& lines) {
	std::string result;
	for (size_t i = 0; i < lines.size(); ++i) {
		if (i > 0) result += " / ";
		result += lines[i];
	}
	return result;
}

// Build memory context string for injection into the AI prompt
std::string BuildMemoryContext() {
	std::string context;

	// Add notes if present
	if (!memory_notes.empty()) {
		context += "\nPREVIOUS SESSION NOTES (maintain these themes/style):\n";
		std::string notes = memory_notes;
		if (notes.size() > 500) notes = notes.substr(0, 497) + "...";
		context += notes + "\n";
	}

	// Add recent short-term entries (this session)
	if (!short_term_memory.empty()) {
		context += "\nRECENT DIALOGUE THIS SESSION (maintain continuity):\n";
		size_t start_idx = short_term_memory.size() > 5 ? short_term_memory.size() - 5 : 0;
		for (size_t i = start_idx; i < short_term_memory.size(); ++i) {
			std::string orig = short_term_memory[i].original;
			std::string rewr = short_term_memory[i].rewritten;
			if (orig.size() > 150) orig = orig.substr(0, 147) + "...";
			if (rewr.size() > 150) rewr = rewr.substr(0, 147) + "...";
			context += "- Original: " + orig + "\n  Rewritten: " + rewr + "\n";
		}
	}

	// Add long-term entries (from past sessions)
	if (!long_term_memory.empty()) {
		context += "\nDIALOGUE FROM PREVIOUS SESSIONS (for style consistency):\n";
		size_t start_idx = long_term_memory.size() > 5 ? long_term_memory.size() - 5 : 0;
		for (size_t i = start_idx; i < long_term_memory.size(); ++i) {
			std::string orig = long_term_memory[i].original;
			std::string rewr = long_term_memory[i].rewritten;
			if (orig.size() > 150) orig = orig.substr(0, 147) + "...";
			if (rewr.size() > 150) rewr = rewr.substr(0, 147) + "...";
			context += "- Original: " + orig + "\n  Rewritten: " + rewr + "\n";
		}
	}

	return context;
}

// Update memory after a successful rewrite
void UpdateMemoryAfterRewrite() {
	for (auto& entry : cached_entries) {
		if (entry.rewritten.empty()) continue;

		MemoryEntry mem;
		mem.original = CompactDialogue(entry.original);
		mem.rewritten = CompactDialogue(entry.rewritten);
		mem.timestamp = static_cast<int64_t>(std::time(nullptr));

		// Add to short-term
		short_term_memory.push_back(mem);
		if (short_term_memory.size() > MAX_SHORT_TERM) {
			short_term_memory.erase(short_term_memory.begin());
		}

		// Add to long-term
		long_term_memory.push_back(std::move(mem));
		if (long_term_memory.size() > MAX_LONG_TERM) {
			long_term_memory.erase(long_term_memory.begin());
		}
	}

	SaveMemoryToFile();
}

} // anonymous namespace

namespace Chaos {
namespace AIRewriter {

bool IsEnabled() {
	return ai_rewriter_enabled;
}

void SetEnabled(bool enabled) {
	ai_rewriter_enabled = enabled;
	cached_entries.clear();
	cached_index = 0;
	cached_event_id = 0;
	overflow_queue.clear();
	if (enabled && !memory_loaded) {
		LoadMemoryFromFile();
		++session_count;
		SaveMemoryToFile();
	}
	Output::Debug("Chaos AI Rewriter: {}", enabled ? "enabled" : "disabled");
}

void LoadMemory() {
	LoadMemoryFromFile();
}

void SaveMemory() {
	SaveMemoryToFile();
}

void ConsolidateMemory() {
	if (long_term_memory.size() < 5) return;

	// Build a summary request from recent entries
	std::string entries_text;
	size_t start_idx = long_term_memory.size() > 20 ? long_term_memory.size() - 20 : 0;
	for (size_t i = start_idx; i < long_term_memory.size(); ++i) {
		entries_text += "Original: " + long_term_memory[i].original + "\n";
		entries_text += "Rewritten: " + long_term_memory[i].rewritten + "\n\n";
	}

	std::string consolidation_user =
		"Analyze these RPG dialogue rewriting examples and produce concise notes about:\n"
		"- Recurring character personalities and traits\n"
		"- Running gags or jokes\n"
		"- Style patterns and themes\n"
		"Keep it under 500 characters total. Be specific about named characters.\n\n" +
		entries_text;

	std::string payload =
		"{\"model\":\"" + std::string(MODEL) + "\","
		"\"messages\":["
		"{\"role\":\"system\",\"content\":\"You are a concise note-taker. Summarize dialogue patterns.\"}"
		",{\"role\":\"user\",\"content\":\"" + JsonEscape(consolidation_user) + "\"}"
		"],\"max_tokens\":512,\"temperature\":0.5}";

	CURL* curl = curl_easy_init();
	if (!curl) return;

	std::string response_body;
	std::string auth_header = std::string("Authorization: Basic ") + API_KEY;

	struct curl_slist* headers = nullptr;
	headers = curl_slist_append(headers, auth_header.c_str());
	headers = curl_slist_append(headers, "Content-Type: application/json");

	curl_easy_setopt(curl, CURLOPT_URL, API_URL);
	curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
	curl_easy_setopt(curl, CURLOPT_POSTFIELDS, payload.c_str());
	curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteCallback);
	curl_easy_setopt(curl, CURLOPT_WRITEDATA, &response_body);
	curl_easy_setopt(curl, CURLOPT_TIMEOUT, 15L);
	curl_easy_setopt(curl, CURLOPT_CONNECTTIMEOUT, 5L);

	Output::Debug("Chaos AI Memory: consolidating {} entries into notes...", long_term_memory.size());

	CURLcode res = curl_easy_perform(curl);
	long http_code = 0;
	curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &http_code);

	curl_slist_free_all(headers);
	curl_easy_cleanup(curl);

	if (res != CURLE_OK || http_code != 200) {
		Output::Debug("Chaos AI Memory: consolidation failed (HTTP {})", http_code);
		return;
	}

	std::string content = ExtractContent(response_body);
	if (!content.empty()) {
		memory_notes = content;
		if (memory_notes.size() > 500) {
			memory_notes = memory_notes.substr(0, 497) + "...";
		}
		SaveMemoryToFile();
		Output::Debug("Chaos AI Memory: notes updated: {}", memory_notes);
	}
}

bool HasOverflow() {
	return !overflow_queue.empty();
}

std::vector<std::string> PopOverflow() {
	if (overflow_queue.empty()) return {};
	auto front = std::move(overflow_queue.front());
	overflow_queue.erase(overflow_queue.begin());
	return front;
}

bool HasCachedMessages(uintptr_t event_id) {
	return event_id == cached_event_id && cached_index < cached_entries.size();
}

std::vector<std::string> PopRewrittenMessage(const std::vector<std::string>& original_lines) {
	// Clear any leftover overflow before popping a new message
	overflow_queue.clear();

	if (cached_index >= cached_entries.size()) return {};

	std::vector<std::string>* rewritten_ptr = nullptr;

	// Try sequential match first (common case: no branches)
	if (cached_entries[cached_index].original == original_lines) {
		rewritten_ptr = &cached_entries[cached_index++].rewritten;
	} else {
		// Search forward for matching entry (handles skipped branches)
		for (size_t i = cached_index + 1; i < cached_entries.size(); ++i) {
			if (cached_entries[i].original == original_lines) {
				cached_index = i + 1;
				rewritten_ptr = &cached_entries[i].rewritten;
				break;
			}
		}
	}

	if (!rewritten_ptr) {
		// No match — cache is stale, clear and let caller use original
		Output::Debug("Chaos AI Rewriter: cache mismatch, clearing");
		cached_entries.clear();
		cached_index = 0;
		cached_event_id = 0;
		return {};
	}

	auto& rewritten = *rewritten_ptr;

	// If rewritten text fits in one box, return as-is
	if (rewritten.size() <= MAX_LINES_PER_BOX) {
		return std::move(rewritten);
	}

	// Split into 4-line boxes: first box returned now, rest queued as overflow
	auto boxes = SplitIntoBoxes(rewritten);
	auto first_box = std::move(boxes[0]);
	for (size_t b = 1; b < boxes.size(); ++b) {
		overflow_queue.push_back(std::move(boxes[b]));
	}

	Output::Debug("Chaos AI Rewriter: split into {} boxes ({} overflow)",
		boxes.size(), overflow_queue.size());

	return first_box;
}

void CollectAndRewriteEvent(uintptr_t event_id, const std::vector<std::vector<std::string>>& all_messages, bool has_face) {
	cached_entries.clear();
	cached_index = 0;
	cached_event_id = event_id;

	if (!ai_rewriter_enabled || all_messages.empty()) {
		return;
	}

	// ── Lazy-load memory on first use ─────────────────────────────────────
	if (!memory_loaded) {
		LoadMemoryFromFile();
		++session_count;
	}

	// ── Rate limiting ──────────────────────────────────────────────────────
	auto now = Clock::now();
	if (last_call_time != Clock::time_point{} && (now - last_call_time) < RATE_DELAY) {
		Output::Debug("Chaos AI Rewriter: rate-limited, returning original dialogue");
		return;
	}

	// ── Strip format codes and record leading whitespace per line ──────────
	// prefixes[m][i] = leading whitespace + format codes for message m, line i
	std::vector<std::vector<std::string>> prefixes(all_messages.size());
	std::vector<std::vector<std::string>> clean_messages(all_messages.size());

	for (size_t m = 0; m < all_messages.size(); ++m) {
		prefixes[m].resize(all_messages[m].size());
		clean_messages[m].resize(all_messages[m].size());
		for (size_t i = 0; i < all_messages[m].size(); ++i) {
			auto [ws, rest] = SplitLeadingWhitespace(all_messages[m][i]);
			prefixes[m][i] = ws;
			clean_messages[m][i] = StripFormatCodes(rest);
		}
	}

	// ── Build the user message with all messages separated by --- ──────────
	int total_lines = 0;
	std::string combined;
	for (size_t m = 0; m < clean_messages.size(); ++m) {
		if (m > 0) combined += "\n---\n";
		for (size_t i = 0; i < clean_messages[m].size(); ++i) {
			if (i > 0) combined += "\n";
			combined += clean_messages[m][i];
			++total_lines;
		}
	}

	// ── Build memory context ───────────────────────────────────────────────
	std::string mem_context = BuildMemoryContext();

	std::string user_msg =
		"Rewrite this RPG event dialogue. There are " +
		std::to_string(all_messages.size()) + " message boxes separated by ---.\n"
		"Keep EXACTLY the same number of message boxes. "
		"You can use as many lines as you want per box.\n"
		"Do NOT add any leading whitespace or indentation to your output.\n"
		"Separate your rewritten message boxes with --- on its own line.\n";

	if (!mem_context.empty()) {
		user_msg += mem_context + "\n";
	}

	user_msg += combined;

	// ── Build JSON payload ─────────────────────────────────────────────────
	std::string payload =
		"{"
		"\"model\":\"" + std::string(MODEL) + "\","
		"\"messages\":["
		"{\"role\":\"system\",\"content\":\"" + JsonEscape(SYSTEM_PROMPT) + "\"},"
		"{\"role\":\"user\",\"content\":\"" + JsonEscape(user_msg) + "\"}"
		"],"
		"\"extra_body\":{"
		"\"models\":[\"xai/grok-4-1-fast-reasoning\",\"google-ai-studio/gemini-3.1-flash-lite-preview\"],"
		"\"sort\":[\"price\"]"
		"},"
		"\"max_tokens\":8192,"
		"\"temperature\":1.2"
		"}";

	// ── curl request ───────────────────────────────────────────────────────
	CURL* curl = curl_easy_init();
	if (!curl) {
		Output::Warning("Chaos AI Rewriter: curl_easy_init failed");
		return;
	}

	std::string response_body;
	std::string auth_header = std::string("Authorization: Basic ") + API_KEY;

	struct curl_slist* headers = nullptr;
	headers = curl_slist_append(headers, auth_header.c_str());
	headers = curl_slist_append(headers, "Content-Type: application/json");

	curl_easy_setopt(curl, CURLOPT_URL, API_URL);
	curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
	curl_easy_setopt(curl, CURLOPT_POSTFIELDS, payload.c_str());
	curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteCallback);
	curl_easy_setopt(curl, CURLOPT_WRITEDATA, &response_body);
	curl_easy_setopt(curl, CURLOPT_TIMEOUT, 30L);
	curl_easy_setopt(curl, CURLOPT_CONNECTTIMEOUT, 10L);

	Output::Debug("Chaos AI Rewriter: sending {} messages ({} total lines) to Inworld API...",
		all_messages.size(), total_lines);

	CURLcode res = curl_easy_perform(curl);

	long http_code = 0;
	curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &http_code);

	curl_slist_free_all(headers);
	curl_easy_cleanup(curl);

	// Record the call time regardless of outcome (for rate limiting)
	last_call_time = Clock::now();

	if (res != CURLE_OK) {
		Output::Warning("Chaos AI Rewriter: curl error: {}", curl_easy_strerror(res));
		return;
	}

	if (http_code != 200) {
		Output::Warning("Chaos AI Rewriter: HTTP {}: {}", http_code,
			response_body.size() > 300 ? response_body.substr(0, 300) : response_body);
		return;
	}

	// ── Parse response ─────────────────────────────────────────────────────
	std::string content = ExtractContent(response_body);
	if (content.empty()) {
		Output::Warning("Chaos AI Rewriter: failed to parse response content");
		return;
	}

	Output::Debug("Chaos AI Rewriter: raw response: {}", content);

	// Split response into message blocks by "---"
	auto all_lines = SplitLines(content);
	std::vector<std::vector<std::string>> result_messages;
	std::vector<std::string> current_block;

	for (auto& line : all_lines) {
		// Trim whitespace for separator detection
		std::string trimmed = line;
		while (!trimmed.empty() && (trimmed.front() == ' ' || trimmed.front() == '\t')) {
			trimmed.erase(trimmed.begin());
		}
		while (!trimmed.empty() && (trimmed.back() == ' ' || trimmed.back() == '\t')) {
			trimmed.pop_back();
		}

		if (trimmed == "---") {
			if (!current_block.empty()) {
				result_messages.push_back(std::move(current_block));
				current_block.clear();
			}
		} else {
			current_block.push_back(std::move(line));
		}
	}
	if (!current_block.empty()) {
		result_messages.push_back(std::move(current_block));
	}

	// ── Match up with original message structure, word-wrap, reapply formatting ──
	for (size_t m = 0; m < all_messages.size(); ++m) {
		CachedMessage entry;
		entry.original = all_messages[m];

		if (m < result_messages.size()) {
			auto& raw_rewritten = result_messages[m];

			// Get the prefix from the first line of the original (for word-wrap)
			std::string first_prefix = (m < prefixes.size() && !prefixes[m].empty())
				? prefixes[m][0] : "";

			// Word-wrap each AI line and reapply original leading whitespace
			std::vector<std::string> wrapped_lines;
			for (size_t i = 0; i < raw_rewritten.size(); ++i) {
				// Strip any AI-generated leading whitespace
				std::string stripped = raw_rewritten[i];
				size_t start = 0;
				while (start < stripped.size() && (stripped[start] == ' ' || stripped[start] == '\t')) {
					++start;
				}
				stripped = stripped.substr(start);

				// Use original prefix for first few lines, first_prefix for overflow
				std::string prefix = (i < prefixes[m].size()) ? prefixes[m][i] : first_prefix;

				// Word-wrap this line
				auto sub_lines = WordWrap(prefix, stripped, has_face);
				for (auto& sl : sub_lines) {
					wrapped_lines.push_back(std::move(sl));
				}
			}

			entry.rewritten = std::move(wrapped_lines);
		} else {
			// AI didn't produce enough blocks — use original
			entry.rewritten = all_messages[m];
		}

		cached_entries.push_back(std::move(entry));
	}

	Output::Debug("Chaos AI Rewriter: cached {} rewritten messages", cached_entries.size());

	// ── Update memory with this rewrite ────────────────────────────────────
	UpdateMemoryAfterRewrite();

	// ── Periodically consolidate memory into notes ────────────────────────
	static int rewrites_since_consolidation = 0;
	++rewrites_since_consolidation;
	if (rewrites_since_consolidation >= 10) {
		rewrites_since_consolidation = 0;
		ConsolidateMemory();
	}
}

} // namespace AIRewriter
} // namespace Chaos
